---
- name: Checking variable precedence
  hosts: centos
  vars_files:
  #   - variables/vars.yaml
  vars:
    color: red
  tasks:
    - name: Display color
      ansible.builtin.debug:
        msg:
          - The color is {{ color }}
      register: result

    - name: Display register variable
      ansible.builtin.debug:
        var: result
      
