download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-aap_configuration-3.1.0.tar.gz
format_version: 1.0.0
name: aap_configuration
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/infra/aap_configuration/versions/3.1.0/
