---
- name: Role User Assignments | Configuration # noqa fqcn[action-core]
  ansible.platform.role_user_assignment:
    role_definition: "{{ __gateway_role_user_assignments_item.role_definition | mandatory }}"
    user: "{{ __gateway_role_user_assignments_item.user | default(omit) }}"
    user_ansible_id: "{{ __gateway_role_user_assignments_item.user_ansible_id | default(omit) }}"
    object_id: "{{ __gateway_role_user_assignments_item.object_id | default(omit) }}"
    object_ansible_id: "{{ __gateway_role_user_assignments_item.object_ansible_id | default(omit) }}"
    state: "{{ __gateway_role_user_assignments_item.state | default(platform_state | default(omit, true)) }}"

    # Role Standard Options
    gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
    gateway_username: "{{ aap_username | default(omit, true) }}"
    gateway_password: "{{ aap_password | default(omit, true) }}"
    gateway_token: "{{ aap_token | default(omit, true) }}"
    gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
    gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
  loop: "{{ gateway_role_user_assignments }}"
  loop_control:
    loop_var: __gateway_role_user_assignments_item
    label: "{{ __operation.verb }} Role Based Access Entry on Controller {{ __gateway_role_user_assignments_item.1 | default(__gateway_role_user_assignments_item.role_definition) }}"
    pause: "{{ gateway_role_user_assignments_loop_delay }}"
  no_log: "{{ gateway_role_user_assignments_secure_logging }}"
  async: 1000
  poll: 0
  register: __gateway_role_user_assignments_job_async
  changed_when: not __gateway_role_user_assignments_job_async.changed
  vars:
    __operation: "{{ operation_translate[__gateway_role_user_assignments_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"

- name: Role User Assignments | Wait for finish the configuration
  ansible.builtin.async_status:
    jid: "{{ __gateway_role_user_assignments_job_async_results_item.ansible_job_id }}"
  register: __gateway_role_user_assignments_job_async_result
  until: __gateway_role_user_assignments_job_async_result.finished
  retries: "{{ gateway_role_user_assignments_async_retries }}"
  delay: "{{ gateway_role_user_assignments_async_delay }}"
  loop: "{{ __gateway_role_user_assignments_job_async.results }}"
  loop_control:
    loop_var: __gateway_role_user_assignments_job_async_results_item
    label: "{{ __operation.verb }} Role {{ __gateway_role_user_assignments_job_async_results_item.__gateway_role_user_assignments_item.1 | default(__gateway_role_user_assignments_job_async_results_item.__gateway_role_user_assignments_item.role_definition) }} | Wait for finish the Roles {{ __operation.action }}"
  when: __gateway_role_user_assignments_job_async_results_item.ansible_job_id is defined
  no_log: "{{ gateway_role_user_assignments_secure_logging }}"
  vars:
    __operation: "{{ operation_translate[__gateway_role_user_assignments_job_async_results_item.__controller_role_item.state | default(platform_state) | default('present')] }}"
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
...
