---
eda_credential_types: []
eda_configuration_credential_types_secure_logging: "{{ aap_configuration_secure_logging | default(true) }}"
eda_configuration_credential_types_async_retries: "{{ aap_configuration_async_retries | default(50) }}"
eda_configuration_credential_types_async_delay: "{{ aap_configuration_async_delay| default(1) }}"
aap_configuration_async_dir:
...
